name: check disk
run-name: check disk
on:
  push:
  pull_request:
env:
  ZSDK_VERSION: 0.17.0-rc2
  FVP_BASE_REVC_VERSION: 11.24_11

jobs:
  After_check:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        attempt: [1]
      fail-fast: false

    container:
      image: ghcr.io/zephyrproject-rtos/ci-base:latest
      options: '--entrypoint /bin/bash'

    steps:
      - name: check disk
        run: |
          df -h
          echo "GITHUB_WORKSPACE==${GITHUB_WORKSPACE}"
          ls -al $GITHUB_WORKSPACE
          du -h --max-depth=1 / 2>/dev/null

  