name: Build ZMK
run-name: ${{ github.event_name }} by ${{ github.actor }}
on: 
  push:
  pull_request:

jobs:
  Build-ZMK:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.26.11
      options: '--entrypoint /bin/bash'

    steps:
      - name: set_env
        run: |
          if [ "${{ github.event_name }}" = "pull_request" -o "${{ github.event_name }}" = "pull_request_target" ];then
            echo "This is pull request"
            echo "EVENT_TRIGER_REF=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          fi

          if [ "${{ github.event_name }}" = "push" ];then
            echo "This is push"
            echo "EVENT_TRIGER_REF=${{ github.ref }}" >> $GITHUB_ENV
          fi

      - name: print_env
        run: |
          echo "sdk-version -> ${ZSDK_VERSION}"
          echo "event_triger_ref: ${EVENT_TRIGER_REF}"
  
      - id: checkout-build 
        uses: catherine-guo-2024/actions-west-checkout-for-event@v1.0
        with:
          event-trigger-ref: ${{ github.event.pull_request.head.sha || github.ref }}
          zephyr-manifest-repository: "rtkconnectivity/zmk.git"
          zephyr-manifest-ref: "zmk_rtk"
          zephyr-manifest-local-path: "zmk"
          west-root-path: "zmk"
          west-init-cmd: "-l app"

      - name: do-build
        run: |
          cd zmk/zephyr
          cd ../app
          west forall -c "git log -1 --pretty=oneline"
          west build -p -b rtl8762gn_evb -- -DSHIELD=rtk_keyboard

